# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncLzknAftc9wGuG-tXeIGrHdyxydK1Xq
"""

import networkx as nx
import matplotlib.pyplot as plt

# Grafo Orientado
G = nx.DiGraph ()

G.add_nodes_from(["Elvis", "Fa-1", "Fa-2", "Fa-3", "Nao-fa"])

# Adicionar Arestas
G.add_edges_from([("Fa-1", "Elvis"),
                  ("Fa-2", "Elvis"),
                  ("Fa-3", "Elvis"),])

print(f"Nós do Grafo : {G.nodes()}")
print(f"Arestas do Grafo : {G.edges()}")

pos = nx.spring_layout(G, seed=42)

nx.draw(G, pos, with_labels=True, node_color="red",
              node_size=2000, font_color="white", font_size=7, arrowsize=15)

plt.title("Representação em Grafo Direcionado")
plt.show()